"""
@Title: 
@Author(s): Stephen CUI
@LastEditor(s): Stephen CUI
@CreatedTime: 2023-09-04 16:44:37
@Description: 
"""


# def product(x, y):
#     pass


# 如果运行将出现 python test_my_math.py：

# """
# FF
# ======================================================================
# FAIL: test_floats (__main__.ProductTestCase.test_floats)
# ----------------------------------------------------------------------
# Traceback (most recent call last):
#   File "C:\Notes\Python-3\BP-3rd\code\ch16\test_my_math.py", line 26, in test_floats
#     self.assertEqual(p, x * y, "Float multiplication failed")
# AssertionError: None != 1.0 : Float multiplication failed

# ======================================================================
# FAIL: test_integers (__main__.ProductTestCase.test_integers)
# ----------------------------------------------------------------------
# Traceback (most recent call last):
#   File "C:\Notes\Python-3\BP-3rd\code\ch16\test_my_math.py", line 18, in test_integers
#     self.assertEqual(p, x * y, "Integer multiplication failed")
# AssertionError: None != 100 : Integer multiplication failed

# ----------------------------------------------------------------------
# Ran 2 tests in 0.001s

# FAILED (failures=2)
# """

def product(x, y):
    return x * y
# ..
# ----------------------------------------------------------------------
# Ran 2 tests in 0.001s

# OK
